### ISSUE TITLE
Available image format?

### ISSUE THREAD

**Issue by kyoheiu** [hpjansson/chafa#101]
Hi,
I'd like to use chafa in my TUI file manager https://github.com/kyoheiu/felix to show image preview, but is there a list of image (and video?) format that chafa can convert?
Thanks in advance.

**Comment by hpjansson** [comment]
Hey, that looks like a cool project. If you issue `chafa --version`, you will see a line that says `Loaders: ...`. That's the list of supported formats.

GIF, PNG and XWD are built-in and will always be present. There can be other formats, but those are optional and depend on how Chafa was built. Unfortunately there is no video support yet, only animated GIF and WebP. There may be ffmpeg support at some point, see https://github.com/hpjansson/chafa/issues/98.

If "ImageMagick" is listed, that means we support all the ImageMagick formats (i.e. `identify -list format`) as a fallback. ImageMagick support will be removed soon, though, due to dependency/security concerns. If there are unusual image/video formats you want to see support for, feel free to open issues (or even better, PRs).

At some point it would also be nice to have Rust bindings for libchafa.

**Comment by kyoheiu** [comment]
Thank you for the details! So at least GIF, PNG, and XWD are supported, and the other formats depend on the user's environment, which means it is difficult to determine in advance exactly which formats are supported, right?
(I don't think it is necessary to determine exactly though).

**Comment by hpjansson** [comment]
Sorry, forgot to add that with all optional loaders compiled in, the list looks like this:

`GIF ImageMagick JPEG PNG SVG TIFF WebP XWD`

**Comment by hpjansson** [comment]
Right, it depends on the platform. Packaging has been pretty good, though -- every Linux distro I've checked builds in all the loaders above.

**Comment by kyoheiu** [comment]
Thank you again!
FYI, in macOS (11.6 BIg Sur, Intel) the list is `GIF ImageMagick JPEG PNG TIFF WebP XWD`.

**Comment by kyoheiu** [comment]
I released felix v1.1.0 https://github.com/kyoheiu/felix , which uses `chafa` binary to preview image files. Thank you for making this great software!
