### ISSUE TITLE
Image is kinda blurry compared to `img2sixel`

### ISSUE THREAD

**Issue by ErrorNoInternet** [hpjansson/chafa#119]
Images displayed by chafa are slightly blurrier than ones displayed by img2sixel (libsixel)
Also, the ones displayed by chafa are a few pixels shorter (in height) compared to the ones by `img2sixel` I think (not sure if that's actually the case or maybe it's just my eyes). Maybe that's why it's blurrier? See the image below:
![image](https://user-images.githubusercontent.com/61157623/206905783-fcaf756a-5b1d-46b0-83d4-ea1010a0ba28.png)
And the original image:
![termtest](https://user-images.githubusercontent.com/61157623/206905898-bd20ab0f-93e3-42d5-b1d8-613d03fa3632.png)

Using Konsole 22.12.0

**Comment by hpjansson** [comment]
Hi! Thanks for filing the report.

You're right, it's blurrier. The reason is that Chafa internally handles dimensions as cell extents, not pixels. The image is scaled to fit a certain number of text cells exactly: When I first defined the API, I hadn't considered pixel-perfect graphics (originally it only did ANSI art).

I have ideas on how to fix it, but it requires some API finesse (e.g. how to align the image in the cell extent it occupies -- left, right, center). This issue seems like a good place to track the progress :-)

**Comment by hpjansson** [comment]
I've been working on extending [my image library](https://github.com/hpjansson/smolscale) to allow simultaneous scaling and subpixel translation, which will fix the problem once it's done. Of couse it succumbed to feature creep (sRGB! _Fast_ sRGB! More AVX! New tests and benchmarks! _Even more_ AVX!), but it's getting there on my local branch. Arguments for image alignment are also being added (discussion in #140).
