### ISSUE TITLE
NoDecodeDelegateForThisImageFormat PNG & JPG on Arm64

### ISSUE THREAD

**Issue by WuShufei** [hpjansson/chafa#129]
Running chafa from snapd on a Raspad with raspberry pi 4B with Raspbian 64bit.  It was the only way I could get chafa (1.7) to work, whether from binary, source, or apt repo.  Chafa will transcode gifs fine.  But jpgs and pngs receive “Error loading Foo.png : NoDecodeDelegateForThisImage ‘PNG’ @ error/constitute.c/ReadImage/504”.  Any help with this would be fab?

**Comment by hpjansson** [comment]
Hmmm. So the binaries not working isn't so strange, since those are for x86_64. What I think could be the issue here is that you may be getting an old version of Chafa that uses ImageMagick's PNG and JPG loaders, and there's a problem with IM on your system.

What does `chafa --version` say?

**Comment by WuShufei** [comment]
`ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Chafa version 1.7.0

Features: none
Applying: none

Copyright (C) 2018-2021 Hans Petter Jansson et al.
Incl. libnsgif copyright (C) 2004 Richard Wilson, copyright (C) 2008 Sean Fox

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

When trying to use the --help file example, for instance, on a test pattern, this is what comes up:

`chafa -c 16 --color-space din99d --symbols -dot-stipple tv-test-pattern-bbc.jpg 
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
/snap/chafa/3/bin/chafa: Error loading 'tv-test-pattern-bbc.jpg': NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/504
`

**Comment by WuShufei** [comment]
I got chafa working by building from git source, version 1.13.0.  But it required the `--enable-rpath` argument on the autogen script to work on Raspbian, as outlined in [https://github.com/hpjansson/chafa/issues/73](url) . I'm not sure what's going on with the Snap version, but it would probably help to update that, whoever stocks that shelf.  Anyway, I have it working now, and it looks adorable!

**Comment by hpjansson** [comment]
Glad you got it working, and thanks for the kind comment! I was confused by Snap having 1.7, since that's an unreleased version. It probably came from git or (currently unmaintained) nightlies.

I try not to get too involved in packaging, for two reasons: a) There are lots of distributions, and for me to figure out the details of each one wouldn't scale and b) the actual packagers work for their users, not for me. So I think the ideal way to address this is for you or another Raspbian user to find the packager and ask if they can upgrade/fix their package. I'll of course assist if I can.

As a side note, Repology seems to think [Raspbian Testing has the latest and greatest](https://repology.org/project/chafa/versions), which should mean you'd be able to get it through apt at some point. Newer Chafa versions use internal loaders, so ImageMagick breaking will be less of a problem as distributions upgrade.

**Comment by hpjansson** [comment]
Looks like nothing left to do here. Closing.
