### ISSUE TITLE
Poor quality in Alacritty

### ISSUE THREAD

**Issue by Mohamed-Fathy-Salah** [hpjansson/chafa#136]
`chafa a.png`
![image](https://user-images.githubusercontent.com/60598620/224028487-20afb6fd-455b-48a5-820a-816e88c4b15a.png)

terminal used: alacritty 0.11.0

**Comment by wisonye** [comment]
> Hi, thanks for reporting this issue. We're using text glyph rendering on Alacritty, since the last time I checked it didn't support a better image protocol like sixel, kitty, etc.
> 
> Does it look a bit better with `chafa -w 9 a.png`? How about `chafa -w 9 --color-extractor median`?

Hi there, I got the same result here with `Alacritty`, and the command above doesn't improve anything, let me know if you need more info, love to help to solve it (if possible) :smile:

**Comment by hpjansson** [comment]
I think the underlying issue here is that Alacritty doesn't support pixel-for-pixel images, so we're falling back to character-cell mosaics. [There's a long discussion discussion of image protocols in Alacritty's tracker](https://github.com/alacritty/alacritty/issues/910). Looks like there isn't technically any opposition to implementing it, but no one has stepped up yet.

So our issue becomes a matter of managing expectations (how good can character mosaics get?) and maybe adjusting the defaults to improve the results you're getting.

Here's another thing you can try: `chafa -w 9 --symbols block a.png`

That disables use of the border symbols, which gives a more blocky look that some (many?) people prefer. Does the result look better to you?

**Comment by wisonye** [comment]
> 

Yes, it does look a bit better:) But still, I prefer to use my image drawing script to show the image outside the terminal. Hopefully, Alacritty team will do something in the future:)

**Comment by hpjansson** [comment]
Great. Since we're stuck with character-cell mosaics in Alacritty, I'll close this issue. Thanks for reporting and chiming in. I'll play around with the defaults a bit for the next release to see if we can get some small improvements there.

**Comment by hpjansson** [comment]
Great. Since we're stuck with character-cell mosaics in Alacritty, I'll close this issue. Thanks for reporting and chiming in. I'll play around with the defaults a bit for the next release to see if we can get some small improvements there.

**Comment by j4james** [comment]
FYI, Alacritty has a PR with Sixel support which has been around years (https://github.com/alacritty/alacritty/pull/4763). The maintainers just don't want to merge it. There's also an Alacritty fork with that Sixel PR included (https://github.com/microo8/alacritty-sixel).

**Comment by FelipeLema** [comment]
is there any means we can tell chafa it's running in the alacritty fork?

**Comment by j4james** [comment]
@FelipeLema I think it should just work automatically, but you can try forcing chafa to use sixel with `chafa -f sixel`.

I'd also now recommend the https://github.com/ayosec/alacritty fork in preference to the one I linked previously, because this one is maintained by the author of the sixel code and is more up to date.
