### ISSUE TITLE
GIF is not looping when detached from within a Bash script

### ISSUE THREAD

**Issue by Delgan** [hpjansson/chafa#143]
Hi. :)

So I'm facing this weird behavior that `chafa file.gif &` works as expected but will stop prematurely when called from a script.

Supposing the file `script.sh` contains:

```bash
chafa file.gif &
sleep 1000
```

Then, calling `bash script.sh` renders the GIF once and finally the `chafa` process stops instead of continuing indefinitely.

Is there an existing workaround to prevent rendering to abort?

I tested with Chafa `1.12.4` on two different terminals (`foot` and `wezterm`).

**Comment by hpjansson** [comment]
That's probably because Chafa looks for a controlling terminal, and if there isn't one attached, it'll assume it's part of a pipeline or a batch processing script and run in batch mode. The idea is that you should be able to do `convert $foo gif:- | chafa` and similar things. Also so there aren't any surprises with infinite loops when a script invokes it with e.g. `chafa *` and it expands to a single file.

You should be able to specify an infinite duration with `-d inf`.

**Comment by Delgan** [comment]
Great! It's working like a charm. :+1:
I tried with `-d infinite` without success, and since I didn't see it mentioned in the `--help`, I assumed it was simply not possible. Now, I understand it probably simply use `strtod` under the hood.

Thank you for the explanations regarding the loop deactivation when inside a Bash script. That makes plain sense.

**Comment by hpjansson** [comment]
No problem, thanks for filing the issue. I think we need to document this better and support `infinite` as an argument.

**Comment by hpjansson** [comment]
Remaining issues addressed in fe55abf1d48ab6f357e0c3602cb5f2d6d3e88dad and 18cfec80352934d604a5bed69f0872fe17a93931.
