### ISSUE TITLE
is README (not README.md) outdated

### ISSUE THREAD

**Issue by Terracotta-Lite** [hpjansson/chafa#154]
There are two READMEs, one markdown document and one plain text. They conflict.

https://github.com/hpjansson/chafa/blob/master/README says I need ImageMagick whilst
https://github.com/hpjansson/chafa/blob/master/README.md says I don't.

I thought ImageMagick dependency was removed a while ago.

**Comment by hpjansson** [comment]
Hi, thanks for reporting this. You're right, it's inconsistent. `README.md` is the up-to-date one -- ImageMagick is optional. I'll fix it shortly.

We have to readmes because what works well on the web (which is what most people will find at first), and what works in the terminal (which this, after all, is made for) are very different things. For instance, it's nice to be able to include images in the web version, but the resulting markdown looks terrible in the terminal.

There are MD converters for the terminal, but I don't know if there's one that counts as a gold standard that we can expect everyone to have installed already. If there is such a thing, and it works well, we could remove the plain `README` eventually.
