### ISSUE TITLE
[optimization] Parallelizing build_ansi_gstring using OpenMP

### ISSUE THREAD

**Issue by cdluminate** [hpjansson/chafa#16]
I still haven't finished reading the code so I'm not sure whether this is doable. The `build_ansi_gstring` function seems to be parallelizable with openmp. Theoretically if we split the process of comparing symbols with different part in the original image into many subtasks, those tasks are independent to each other and would likely to gain a further speed up from parallelization.

**Comment by hpjansson** [comment]
To convert an image to character art using `ChafaCanvas`, the following must happen:

1) Allocate the canvas using `chafa_canvas_new()` possibly passing in a config made with `chafa_canvas_config_new()` and its setters.
2) Call `chafa_canvas_set_contents_rgba8()`. This takes a pixel buffer and converts it to a character art representation in an internal matrix.
3) Call `chafa_canvas_build_ansi()`. This converts the character art matrix into a stream of characters and ANSI control codes, which is returned to the caller. This is where `build_ansi_gstring()` comes in.
4) Cleanup etc.

Something like 95% of the work happens in **2)**, since its complexity is N*M (number of cells times number of candidate symbols). The last time I benchmarked it, **3)** barely registered.

If you look at `chafa_canvas_set_contents_rgba8()`, you'll see calls to `prepare_pixel_data()` and `update_cells()`. Most of the processing happens in those, and they're parallelized using instances of `GThreadPool`.

So maybe parallelizing `build_ansi_gstring()` wouldn't be necessary. There may be other ways to improve performance, though. For instance, if your goal is to make the `chafa` command-line utility run faster, you could look into loading jpeg, png, gif formats as special cases without going through ImageMagick. I think it's adding a lot of overhead that we don't need. We could use faster libraries like turbojpeg (maybe), and implement progressive loading for animated gifs so we don't need to keep all the frames in memory at once.

In general, you should be able to find hotspots by building with `CFLAGS='-g -O2 -fno-inline -fno-omit-frame-pointer`, make sure you have debuginfo installed for glib and other dependencies, and profile chafa with sysprof, oprofile or some other tool.

**Comment by hpjansson** [comment]
@cdluminate Since symbol selection is already parallelized, would you mind if we closed this? We can create new issues for specific performance bottlenecks as we find them.

**Comment by cdluminate** [comment]
@hpjansson ah, sure.
