### ISSUE TITLE
Multiplexer passthrough for graphics protocols

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#162]
Unicode placeholder support was added in Kitty 0.28.0. It looks like we can support this without too much trouble.

@m040601 graciously pointed this out in https://github.com/hpjansson/chafa/issues/116#issuecomment-1704359128. The specification is at https://sw.kovidgoyal.net/kitty/graphics-protocol/#unicode-placeholders.

**Comment by AnonymouX47** [comment]
It'll be great  to see support.

One major thing to note though, is that I believe it does require image ID management (except something has changed since the last time i read the spec).

If image ID management can be gotten out the way, I think it'll be really good. Support for animations will also be underway.

The easiest way, i think, to handle image IDs is leave it to be managed by the user. It's possible to also handle it within via some form of "pre allocation" using image numbers but note that this will require querying the terminal and might not be the best for one-off use cases (i.e when executing `chafa` per image).

The way i see it, it may require more work than expected integrating this into the library... :thinking:

**Comment by hpjansson** [comment]
Good point. We'll have to think a bit about how to allocate image IDs, but in the current API I think the simplest option is just to punt it to the caller, as you're suggesting. The command-line tool (being the prototypical caller) can then save state somewhere between invocations in order to not step on its own images.

**Comment by hpjansson** [comment]
This probably also means you should avoid caching converted images unless you're showing only one image at a time or always show them in the same order. Otherwise you'll get random dropouts. I don't see a way around that, though, since the spec seems to indicate Unicode placeholders can only be used with IDs, not numbers.

**Comment by kovidgoyal** [comment]
Yes, one must use ids as numbers are not even notionally unique and the lifetime of the unicode placeholders is not tied to the referenced image. But note that if you allow for two-way communication, you will get the image id for an image created with number from the terminal. However, this will break in multiplexers, which dont allow two way communication.

**Comment by hpjansson** [comment]
I was able to make passthrough work for all four combinations of [kitty, sixels] x [screen, tmux]. The sixel PT has obvious limitations, so must be enabled manually. We may be able to support it for iTerm2 too, but I don't have a good way to test it (no Mac).

It appears tmux merged sixel support less than a month ago, so we won't need that passthrough for very long. Yay!

To do: A little more documentation work and some testing.
