### ISSUE TITLE
Conhost Compatibility Concerns.

### ISSUE THREAD

**Issue by oshaboy** [hpjansson/chafa#170]
This is actually a 2 feature requests in one. Both to achieve the goal of being compatible with older versions of conhost on Windows. Because it turns out conhost wasn't a terminal emulator for a very long time. It's actually a VGA emulator. So you can write any character at any place without a single escape code and even read the character data from the console. Just like ye-olde VGA card. 

The first one is fairly easy, the ability to convert between unicode transformations. You can do it manually or add an optional iconv dependency so you can convert anything to anything, I actually have a hacked version of iconv that works with Petscii somewhere. Codepage 65001 is nice but it's quite new and was only added in 2015 I think. Having an option to convert the output to UTF-16 before outputting to stdout would be nice. 

The second one is one I tried adding to chafa myself but I had a butcher at the source code and figured out that it would require me to change a lot of internal workings. It's the ability to replace ANSI escape codes with calls to SetConsoleTextAttribute because conhost didn't support ANSI escape codes until WSL became a thing. So versions of windows up until Windows 8.1 did not support ANSI escape codes and instead relied on Windows API calls (which also means that you couldn't save a text image to a file). Considering chafa already supports 16 colors it seems to be a perfect fit, but I noticed Chafa, regardless of output format, expects the data to be in one long GString. So there are 2 solutions, either have a bespoke print function for conhost that parses ANSI escape codes and converts them to SetConsoleTextAttribute calls... or somehow have GString output an array of [CHAR_INFO](https://learn.microsoft.com/en-us/windows/console/char-info-str) without triggering UB.

I'm wondering if compatibility with older (Windows 8 and prior) versions of conhost is something you care about or is conhost out of scope for what chafa is trying to do?

**Comment by hpjansson** [comment]
This sounds like an interesting challenge, but I'm a bit reluctant, since it's a nontrivial amount of code for what seems like a very small niche. I've a couple questions:

* Who is this for? AIUI, retro users are served by DOSBox/ANSI.SYS, and modern users are served by Win 10+ ConHost. This sits awkwardly in the middle -- how many Win7/Win8 users will there be in, say, five years?
* Would you expect support for this in the library API, or would it be sufficient if the option were offered in the CLI tool only?
* Would you be willing to contribute and test the functionality?

**Comment by oshaboy** [comment]
Honestly, this is just an poorly thought out idea I had that is squarely in the "this would be cool" corner. I do not actually expect you to implement at all it I just wanted to throw an idea out in case someone out there decides to put in the effort. I might implement it myself once I find the motivation. 

> Who is this for? AIUI, retro users are served by DOSBox/ANSI.SYS, and modern users are served by Win 10+ ConHost. This sits awkwardly in the middle -- how many Win7/Win8 users will there be in, say, five years?

ANSI.SYS doesn't work unless you are in NTVDM. So it would actually be useful for 32-bit Windows users. As useful as Chafa is in general at least. Which is not very. Though you can just use mintty instead but I think it actually 

> Would you expect support for this in the library API, or would it be sufficient if the option were offered in the CLI tool only? 

I mean, considering you can't pipe attribute data to a file it's probably a good idea to add API support if it ever gets implemented. 

> Would you be willing to contribute and test the functionality?

Yes.

**Comment by hpjansson** [comment]
Fun is allowed! So - here's how I'd do this:

* Implement a `ConHostLegacyDriver` that lives in `tools/chafa/chafa-con-host-legacy-driver.[ch]`.
* Let it take a pre-generated ANSI `GString` and an output file handle as arguments.
* Make it use `chafa_term_info_parse_seq()` repeatedly on the string and make Windows API calls corresponding to the parse results.
* Convert UTF-8 characters to UTF-16 using `g_convert()` ([see the GLib API for this](https://developer-old.gnome.org/glib/stable/glib-Character-Set-Conversion.html); it wraps iconv).
* Implement a new argument to `chafa -f ...` in `tools/chafa/chafa.c`. E.g. `chafa -f oldconhost`. When this mode is selected, it forces 16-color symbol mode and sends the output to the new `ConHostLegacyDriver`.

I think generating the ANSI sequences and then re-parsing them is the simplest way to do this, since the library API will eventually emit cursor positioning sequences etc. and those can't be expressed with an array of CHAR_INFO.

If this is successful, the "driver" could later be moved into the library as part of a new, more high-level API where escape sequences etc. are hidden from the user.

**Comment by hpjansson** [comment]
Actually, the best approach would be to use `chafa_canvas_get_char_at()` and `chafa_canvas_get_raw_colors_at()` for each cells and translate their contents to Windows API calls to draw the cells on the screen.

**Comment by oshaboy** [comment]
Move to #175
