### ISSUE TITLE
segmentation fault with `chafa wallpaper.png` on Windows + Wezterm + bash

### ISSUE THREAD

**Issue by RioNight** [hpjansson/chafa#182]
Windows (from scoop) + Wezterm + bash causes segmentation fault:
```
$ chafa wallpaper.png
Segmentation fault
```

Windows (from scoop) + Wezterm + powershell results in no output at all.

`-f symbol` works on both Windows (from scoop) + Wezterm + bash and powershell.

I'm using the bash shell on windows as provided by the git for windows.
Everything is installed by scoop: `scoop install pwsh git wezterm chafa imagemagick`.

All packages are up-to-date as from scoop.

**Comment by hpjansson** [comment]
Hi, thanks for reporting this! Could you please provide the output from `chafa --version`?

If you have `gdb` installed, are you able to run:

```
gdb chafa
(gdb) run wallpaper.png
[wait for crash]
(gdb) t a a bt
```

and copy the output here? If you can't, that's ok -- the version output will still help.

**Comment by hpjansson** [comment]
Looks like Scoop just packages the binaries I build. That makes it easier for me to try to reproduce the issue here. In the meantime, maybe an older release will work better for you. You can find them here: https://hpjansson.org/chafa/releases/static/

**Comment by hpjansson** [comment]
I haven't been able to trigger the crash here using Scoop. In addition to the above, could you please run and attach the output of:

* `scoop which chafa`
* `scoop which wezterm`
* `scoop which bash`

Do you know if it's `chafa` that's crashing or something else (bash maybe)?

For the missing output issue, it looks like Wezterm doesn't support sixels or kitty on Windows. `-f iterm` works, though, although the images appear undersampled and stretched. These issues aren't present on Linux, so I think that's due to bugs/missing features in the Wezterm Windows build. I think I'll make `-f symbols` the default there in an update.

Tangentially, I noticed the Chafa Windows build is slow when running multithreaded. I already solved that issue for the Linux builds -- will make a new Windows build with the same fix.

**Comment by AnonymouX47** [comment]
Should probably see https://github.com/wez/wezterm/issues/1673#issuecomment-1054311400

**Comment by hpjansson** [comment]
I discovered that the new GLib/GIO I used in order to support librsvg spawns a thread during construction that enumerates file type handlers on Windows. This actually does quite a bit of work interacting with the registry, and threw a warning on my test system when allowed to run long enough. It wouldn't trigger on short-lived jobs because we'd finish before it could get that far.

I uploaded a [new Windows build](https://hpjansson.org/chafa/releases/static/chafa-1.14.0-2-x86_64-windows.zip), version 1.14.0-2, with the background task patched out, since we don't need it.

Feel free to test that one - maybe it fixes the crash, maybe not.

**Comment by RioNight** [comment]
On Windows on mintty, `chafa -f iterm wallpaper.png` shows a large blank screen then shows the command prompt again.
`chafa -f sixels wallpaper.png` outputs nothing.

**Comment by RioNight** [comment]
On Wezterm, `chafa -f iterm wallpaper.png` displays the image in an incorrect ratio and messes up the terminal. For example, typing `ls` after this command appears in the middle of the displayed image.

**Comment by RioNight** [comment]
I can't get the segmentation fault again for some reason. I remember still seeing it after upgrading. I'll try to reproduce it.

**Comment by hpjansson** [comment]
Thanks a lot for your feedback, @RioNight.

I doubt the input image is to blame. My fuzz testing would've found any issues in the loader; although I only fuzz on Linux, so there may be Windows-specific code paths either in Chafa or dependencies that aren't tested. If you want, you can attach it (or any image you get it to crash with) or mail it to me so I can use it for testing.

The most likely culprit is still something that was pulled in by the Windows binary build; I added and upgraded a lot of packages to get librsvg going, and some of them run constructors or spawn threads, as we've seen. I'll keep looking for more issues while I wait for a test case or backtrace.

I think I'll also have to look into binary-only fuzzing on Windows, e.g. with WinAFL.

**Comment by hpjansson** [comment]
One idea - if it's some background thread crashing, running chafa with `-d 10` may help to reproduce it. It'll pause for 10 seconds so there's time for things to go pear-shaped.

**Comment by RioNight** [comment]
It looks like the segfault doesn't happen anymore. I might have mis-remembered getting the segfault again after the upgrade.
However, mintty + chafa doesn't work with -f sixels and -f iterm as aformentioned. I can open an new issue to track those if you'd like.

**Comment by hpjansson** [comment]
Great, that's a relief. Yes, please open a new issue for mintty support.
