### ISSUE TITLE
Infinite redraw while previewing a pdf

### ISSUE THREAD

**Issue by myrrc** [hpjansson/chafa#193]
Hi!

I've encountered a bug where chafa infinitely
redraws pages of a pdf instead of rendering only the first page.

[Asciinema cast](https://disk.yandex.com/d/ivpd6zrCzHZq9g)
(can't upload to asciinema.org as it's too big).
[Video](https://disk.yandex.com/i/dN7jUpo4ZytIEw)

Unfortunately, I can't attach the file here as
it contains sensitive information. Send me a
message at to@myrrc.dev and I'll reply with the
file attached. 

chafa version: 1.8.0 
(reproduces on last chafa in master, though)

terminal: foot version: 1.11.0 -pgo +ime -graphemes -assertions

**Comment by hpjansson** [comment]
Hi, thanks for reporting this. E-mail sent. Quick questions:

* Does `chafa --animate off` resolve the issue? The ImageMagick backend turns PDFs into multiple images, and any multi-image file is treated as an animation.
* Are you positive that you can load PDFs with the latest Chafa? I removed the ImageMagick loader there, so it should really be refusing to load PDFs.

**Comment by hpjansson** [comment]
Thanks for providing the test files! I think it's like I suspected: ImageMagick renders them as multiple pages/frames, meaning they will be shown as an animation. In Chafa version 1.10.0 and later, this can be prevented by invoking Chafa with `--animate off`. In Chafa version 1.14.0 and later (also master), trying to read PDFs will result in "unknown file format" being printed, since I removed ImageMagick support due to dependency and security concerns.

You can confirm that a PDF renders as multiple frames by installing ImageMagick and running `convert foo.pdf foo.gif` on the command line, and then viewing the GIF file with any image viewer that supports animation.

**Comment by myrrc** [comment]
Hi Hans,

Chafa 1.14.0 can read pdfs perfectly ;) At least, in my case the preview is working
correctly (without ImageMagick installed).
So, I guess I'll close this issue, thanks.

**Comment by hpjansson** [comment]
Thanks again!
