### ISSUE TITLE
braille range dot matrix

### ISSUE THREAD

**Issue by kilobyte** [hpjansson/chafa#2]
The Braille range at U+2800..U+28FF provides a set of 2×4 dot matrix glyphs that can be very nicely abused for displaying an image.  This doesn't mesh well with other glyphs used by *chafa* as these have a visible raster, but can be a mode on its own.

It has already been implemented in black&white by me as *brailleimg* and by ImageMagick guys as part of *convert*.  As the latter is shipped in existing packages, I deleted my implementation ([last copy](https://github.com/kilobyte/braillegraph/tree/dbdc4ee8533bc2b5dd0a2b0cbec338edde526ba6)), but the one in *imagemagick* is not only not even mentioned in documentation (``convert image.png image.ubrl``) but also cumbersome to use: there's a pointless header and the image is negated.

So I wonder if you'd want to bundle this with *chafa* — a black&white mode is trivial to add, while color, trickier, is doable — would have a [ZX-Spectrumese feel](https://en.wikipedia.org/wiki/Attribute_clash).

**Comment by hpjansson** [comment]
The Braille range is definitely something I'd want to support. I think it could be integrated generally like the rest of the symbols, by adding a CHAFA_SYMBOL_TAG_BRAILLE [ChafaSymbolTag](https://github.com/hpjansson/chafa/blob/b2eb26ff67af40bc2751152d4d1155018aecd7cc/chafa/chafa-symbol-map.h#L32) and supporting code.

It's a lot of symbols, though. It probably wouldn't make sense to add them all to chafa-symbols.c, but they could be handled specially in chafa-symbol-map.c and the full entries generated in [rebuild_symbols()](https://github.com/hpjansson/chafa/blob/master/chafa/chafa-symbol-map.c#L97) there.

The second hurdle is that it'd probably be pretty slow, since Chafa doesn't scale well with the number of symbols available. I've some ideas about how to fix this generally by quantizing each 8x8 block of the image to two colors and using the resulting silhouette to do lookups in a fuzzy LUT.

In the end you would hopefully get nice b&w output using something like `chafa -c none --symbols braille` as well as subtle improvements to details/grain in high-color modes with `chafa --symbols +braille`.

**Comment by hpjansson** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣶⠀⠀⠀⠀⠀
⠀⠀⠀⣾⡿⠿⠿⠿⠿⠃⠀⠘⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡏⠀⠀⢀⣿⠇
⠀⠀⢰⣿⠁⠀⠀⠀⠀⠀⢀⣀⠀⠀⣀⠀⠀⠀⣀⣀⠀⠀⣀⣤⣄⡀⠀⠀⠀⢀⣠⣄⢠⣿⠁⠀⠀⣸⡟⠀
⠀⠀⣾⣯⣤⣤⣤⡄⠀⠀⣸⡏⠀⠀⢻⣇⢀⣴⠟⠁⢠⡾⠋⠉⢹⡇⠀⢀⣼⠟⠉⠉⣿⡇⠀⠀⠀⣿⠃⠀
⠀⢰⣿⠉⠉⠉⠉⠀⠀⢠⣿⠁⠀⠀⢈⣿⡿⠁⠀⢀⣿⡷⠶⠶⠛⠃⠀⣾⠏⠀⠀⢠⣿⠀⠀⠀⠸⠏⠀⠀
⠀⣾⡏⠀⠀⠀⠀⠀⠀⣼⡇⠀⠀⣴⡟⠹⣧⠀⠀⢸⣿⠀⠀⠀⣠⠀⢰⣿⠀⠀⣠⣾⡇⠀⠀⠀⣀⠀⠀⠀
⠸⠿⠁⠀⠀⠀⠀⠀⠠⠿⠀⠠⠾⠋⠀⠀⠿⠆⠀⠀⠻⠿⠶⠟⠃⠀⠀⠻⠷⠟⠋⠿⠁⠀⠀⠺⠿⠃⠀⠀

by commit dfb149aa8d51918689a15b9da34fed9c68b377a0. 

Using `chafa -c none --symbols braille` produces output like the above. Note the spaces are actually U+2800.

If you find any issues with the output, please let me know.
