### ISSUE TITLE
The images not showing correctly in Konsole terminal

### ISSUE THREAD

**Issue by AmiraliToori** [hpjansson/chafa#204]
I have been using `kew` for playing my music in the terminal for a while now, the kew uses `chafa` for representing the album covers, but there is a problem.
for more information please refer to this [link](https://github.com/ravachol/kew/issues/136).

### The Image:
![image](https://github.com/hpjansson/chafa/assets/103496001/4ad2992c-8bdb-419a-baf0-5b704f2a2988)

**Comment by hpjansson** [comment]
Hi, thanks for filing the bug report! I need a little more information in order to figure this out.

* Try issuing `chafa <image.png>` with one of your images inside konsole. Does it look better that way?
* What is the output from `konsole --version`?
* What is the output from `echo $TERM` and `echo $KONSOLE_VERSION`?

**Comment by AmiraliToori** [comment]
### `chafa <image.png>`:
![image](https://github.com/hpjansson/chafa/assets/103496001/9dd58d21-a36e-44f6-b459-0ad31493ffd0)

Konsole Version: 21.12.3
`echo $TERM`: xterm-256color
`echo $KONSOLE_VERSION`: 211203

**Comment by hpjansson** [comment]
Looks like your Konsole version is too old. You need at least version 22.03.70 for sixel support.

**Comment by hpjansson** [comment]
Closing this. It'll probably work with a newer Konsole - if not, feel free to open a new issue.
