### ISSUE TITLE
"unknown file format" for what appears to be a standard jpg file.

### ISSUE THREAD

**Issue by ploum** [hpjansson/chafa#221]
I stumbled across a particular jpg file which seems to not be recognized by Chafa.

$chafa lexamen_plat1-scaled.jpg 
chafa: Failed to open 'lexamen_plat1-scaled.jpg': Unknown file format

$file lexamen_plat1-scaled.jpg 
lexamen_plat1-scaled.jpg: JPEG image data, progressive, precision 8, 1665x2560, components 4

$apt-cache policy chafa
chafa:
  Installé : 1.14.4-1

![lexamen_plat1-scaled](https://github.com/user-attachments/assets/cac6f0be-2744-4155-b54a-6c064ca2e16c)

**Comment by hpjansson** [comment]
Looks like it's an Adobe CMYK-space JPEG. The decoding fails because libjpeg can't convert from CMYK to RGB. We need to add some code to do this conversion ourselves.

References:
https://github.com/pytorch/vision/pull/7741/files
https://gitlab.gnome.org/GNOME/gegl/-/blob/master/operations/external/jpg-load.c
https://bugzilla.mozilla.org/show_bug.cgi?id=674619

Also, the GEGL and Mozilla references indicate some (or all?) Adobe CMYK images are inverted. We may need to handle markers too - but since there are good references available, it's not a big task.

**Comment by hpjansson** [comment]
Always good to see you here, btw. Hope you're doing well!

**Comment by ploum** [comment]
Hey HP, yeah, still using chafa 100 times a day in offpunk ;-)   But work on coding has been very slow due to my new book coming out. But I hope to make a release soon.

Always a pleasure to discuss with you ;-)

**Comment by ploum** [comment]
Wow, already fixed. That was fast!

**Comment by hpjansson** [comment]
I will read the book :-)
