### ISSUE TITLE
chafa complains about shared libraries

### ISSUE THREAD

**Issue by zerinoid** [hpjansson/chafa#32]
anything I try to do - even `chafa --help` - results in this message

`chafa: error while loading shared libraries: libchafa.so.0: cannot open shared object file: No such file or directory
`

**Comment by hpjansson** [comment]
Thanks for reporting this.

How did you install Chafa? From git master, from a tarball or from OS packages?

What do `which chafa` and `ldd $(which chafa)` show?

**Comment by BRUrban** [comment]
Anecdotally, I hit the same issue and had just forgotten to run ldconfig afterward. Doing so solved the issue for me.

**Comment by hpjansson** [comment]
Problem solved! Thanks for the input.

**Comment by hpjansson** [comment]
`-rpath $(libdir)` solves the problem for now, but it's really working around an issue that belongs to either libtool or Ubuntu. FWIW it looks like other Linux distributions are able to locate the new library in /usr/local/lib/ even when ld.so.cache is not updated. For the most up-to-date details, see [this libtool bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30402).

Also note that `-rpath` these days will generate a DT_RUNPATH entry instead of the deprecated DT_RPATH. It can be overridden with the LD_LIBRARY_PATH environment variable.
