### ISSUE TITLE
cannot compile example

### ISSUE THREAD

**Issue by sallyx** [hpjansson/chafa#34]
Hi,
I have installed chafa as package Version: 1.2.1-1 (in Ubuntu).

pkg-config --cflags --libs chafa

returns

-I/usr/include/chafa -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lchafa -lm -lglib-2.0

Trying compile example from https://hpjansson.org/chafa/ref/chafa-using.html i got this error:

 In file included from /usr/include/chafa/chafa.h:29,
                  from example.cpp:1:
 /usr/include/chafa/chafa-version-macros.h:112:2: error: #error "CHAFA_VERSION_MIN_REQUIRED must be >= CHAFA_VERSION_1_0"
   112 | #error "CHAFA_VERSION_MIN_REQUIRED must be >= CHAFA_VERSION_1_0"

If I delete the 112 line, I got this error:

cc example.c  `pkg-config --cflags --libs chafa`  -o hello

/usr/bin/ld: /tmp/ccSbs3zs.o: in function `main':
example.c:(.text+0xc5): undefined reference to `chafa_canvas_set_contents_rgba8'
collect2: error: ld returned 1 exit status

**Comment by hpjansson** [comment]
Thanks for reporting this! You've found a bug in the macros that are supposed to warn you if you're using a deprecated symbol, in this case a symbol that's present since version 1.0 but was superseded by a better interface in version 1.2.

The symbol from 1.0 was still supposed to be visible and usable (albeit with a warning), but it's incorrectly being made invisible during the build. Additionally, the `CHAFA_*_VERSION` macros were not being made available to client programs.

I left out a bit of code by mistake in the 1.2 release; I'll add this to master and 1.2 and make a new release on the 1.2 branch shortly.

In the meantime, as a workaround you can replace the `chafa_canvas_set_contents_rgba8()` call in the example with the following:

```c
chafa_canvas_draw_all_pixels (canvas,
                              CHAFA_PIXEL_RGBA8_UNASSOCIATED,
                              pixels,
                              PIX_WIDTH,
                              PIX_HEIGHT,
                              PIX_WIDTH * N_CHANNELS);
```

I will update the example to use this new call too.

**Comment by sallyx** [comment]
Hi, thanks for info. It works with this function! :)

**Comment by hpjansson** [comment]
> Hi, thanks for info. It works with this function! :)

Great. Case closed!
