### ISSUE TITLE
[i386] port chafa to i386 architecture

### ISSUE THREAD

**Issue by cdluminate** [hpjansson/chafa#5]
`chafa-popcnt.c` uses intrinsic `_mm_popcnt_u64` which is not supported by i386.
And the result is that chafa failed to build on i386 architecture:
https://buildd.debian.org/status/package.php?p=chafa

I have successfully ported chafa to i386, with the following patch.

```patch
diff --git a/chafa/chafa-popcnt.c b/chafa/chafa-popcnt.c
index 22b3eb4..0d95e39 100644
--- a/chafa/chafa-popcnt.c
+++ b/chafa/chafa-popcnt.c
@@ -26,7 +26,12 @@
 gint
 chafa_pop_count_u64_builtin (guint64 v)
 {
+#if !defined(CHAFA_REG_BIT32)
     return (gint) _mm_popcnt_u64 (v);
+#else
+    __int32_t* w = (__int32_t*)&v;
+    return (gint) _mm_popcnt_u32(w[0]) + _mm_popcnt_u32(w[1]);
+#endif
 }
 
 void
@@ -34,13 +39,20 @@ chafa_pop_count_vu64_builtin (const guint64 *vv, gint *vc, gint n)
 {
     while (n--)
     {
+#if !defined(CHAFA_REG_BIT32)
         *(vc++) = _mm_popcnt_u64 (*(vv++));
+#else
+	__int32_t* w = (__int32_t*)vv;
+        *(vc++) = _mm_popcnt_u32(w[0]) + _mm_popcnt_u32(w[1]);
+	vv++;
+#endif
     }
 }
 
 void
 chafa_hamming_distance_vu64_builtin (guint64 a, const guint64 *vb, gint *vc, gint n)
 {
+#if !defined(CHAFA_REG_BIT32)
     while (n >= 4)
     {
         n -= 4;
@@ -50,6 +62,15 @@ chafa_hamming_distance_vu64_builtin (guint64 a, const guint64 *vb, gint *vc, gin
         *(vc++) = _mm_popcnt_u64 (a ^ *(vb++));
     }
 
-    while (n--)
+    while (n--) {
         *(vc++) = _mm_popcnt_u64 (a ^ *(vb++));
+    }
+#else
+    __int32_t* aa = (__int32_t*)&a;
+    __int32_t* wb = (__int32_t*)vb;
+    while (n--) {
+        *(vc++) = _mm_popcnt_u32(aa[0]^wb[0]) + _mm_popcnt_u32(aa[1]^wb[1]);
+	wb += 2;
+    }
+#endif
 }
```

reference [_mm_popcnt_u64](https://msdn.microsoft.com/en-us/library/bb531475(v=vs.120).aspx)
[_mm_popcnt_u32](https://msdn.microsoft.com/en-us/library/bb514083(v=vs.120).aspx)

https://github.com/zhengxwen/HIBAG/commit/d50322268e211ae8e9152ddc0d2faacc808d8591

**Comment by hpjansson** [comment]
Thanks for this! I'd like to merge your fix, but it needs a little more work first. In order to detect the 32-bit popcnt automatically, I suggest the following:

In the following configure check: https://github.com/hpjansson/chafa/blob/5ddfe4cd407bad9ba15993a03dd6f595475dd9cd/configure.ac#L215-L228 change AC_COMPILE_IFELSE to AC_LINK_IFELSE. With just that change it should build fine, but you will get the unaccelerated path on i386.

To check for the 32-bit popcnt intrinsic, copy/paste the above test and make one for _mm_popcnt_u32(). Change the AC_DEFINE statements so you get separate 32-bit and 64-bit defines you can use in chafa-popcnt.c.

You also need to turn ac_cv_popcnt_intrinsics into a separate variable for each and have the AM_CONDITIONAL after the tests turn on HAVE_POPCNT_INTRINSICS if either is "yes". This will make sure chafa-popcnt.c still gets built if you only have the 32-bit popcnt.

**Comment by hpjansson** [comment]
Note, if you change the name of the HAVE_POPCNT_INTRINSICS define, you may also have to make corresponding changes in chafa-features.c and chafa-private.h. It may be simpler to keep it around and make it equal to (HAVE_POPCNT32_INTRINSICS || HAVE_POPCNT64_INTRINSICS).

**Comment by cdluminate** [comment]
@hpjansson Thanks for the hint. I added more commits to modify `configure.ac` as you suggested. Autoconf will define `HAVE_POPCNT_INTRINSICS` if either 64bit popcnt or 32bit popcnt is detected. The result is we don't need to change `chafa-features.c` and `chafa-private.h`.

Is #6 acceptable now?

**Comment by cdluminate** [comment]
Oh, by the way, with the original patch, chafa has been successfully built on all architectures that Debian has. See https://buildd.debian.org/status/package.php?p=chafa

**Comment by cdluminate** [comment]
@hpjansson Added a commit to fix (1) and (2). (3) has been fixed by editing the first commit.

**Comment by hpjansson** [comment]
Looks good! Thanks again.

**Comment by Begasus** [comment]
On Haiku 32bit I'm getting an error on this one:
`chafa-popcnt.c:45:10: error: unknown type name '__int32_t'; did you mean 'u_int32_t'?`
I managed to build it changing the type to u_int32_t, but I'm not sure that it would be the right way, maybe someone could have a suggestion that could work?

**Comment by hpjansson** [comment]
It should be fine to just change it to the GLib type `guint32`. Integer types used to be complicated business :)
