### ISSUE TITLE
Produces small glitches in output with some images

### ISSUE THREAD

**Issue by Safari77** [hpjansson/chafa#52]
-w option seems to affect the position and frequency of the glitches.
Tried chafa 1.6.0 and latest git.

Input:
![carmen-in](https://user-images.githubusercontent.com/3876865/109783181-00362e00-7c0a-11eb-8b16-46578e97cd88.jpg)
Output:
![carmen-out](https://user-images.githubusercontent.com/3876865/109783208-075d3c00-7c0a-11eb-9054-cd115ce1d55c.png)

**Comment by hpjansson** [comment]
Thanks for reporting this. I assume the glitches are the squares in the upper left quadrant containing gradients.

My hunch is that this is due to a Unicode character not handled well by the terminal or maybe your font. Try with `--symbols block`, `--symbols border` or `--symbols ascii` and see if you can make it show up then.

I'd like to figure out exactly what's causing it, but need some more information:

* What's your terminal software, and which version of it are you using?
* A dump of the output containing glitches: `chafa image.jpg >out`. Do `cat out` to make sure it contains the glitch, then compress `out` and attach it here along with a screenshot of the image you got from `cat out`.

Note that when redirecting output, you may have to specify terminal size manually, e.g. with `-s 80x50`.

**Comment by Safari77** [comment]
For me the source of the glitches is `geometric`.  [tv](https://github.com/daleroberts/tv) doesn't produce any glitches.
I have gnome-terminal 3.38.3+vte-0.62.3. Roxterm and alacritty are also broken, but kitty 0.19.3 works ok!

![carmen gnome-terminal](https://user-images.githubusercontent.com/3876865/109807927-cc1d3600-7c26-11eb-8dca-481ce6b81bde.png)
[carmen.txt.gz](https://github.com/hpjansson/chafa/files/6076033/carmen.txt.gz)

**Comment by hpjansson** [comment]
It's code point `U+25FC` (black medium square) that's giving you trouble. It has an emoji variant that was introduced in Unicode 6.1.0 (see [here](https://github.com/scott-fleischman/ucd/commit/9eddb77b47fba10d0b023de78be7a3619dfec415#diff-f7475632b2e346112dfc456f75be8569f6e01ee13b572769cba3ef694ccf1675R210-R211)).

The text variant is typically the default in the geometric range, but implementations are free to choose emoji based on context and font support. VTE gives me the text variant here, so it's probably down to fonts.

I'll mark the symbol as ambiguous and do the same with the other geometric symbols with emoji variants, like the right- and left-pointing triangles that somehow double as "play buttons".

Let me know if you find any other issues!
