### ISSUE TITLE
Chafa always looks the same on kitty

### ISSUE THREAD

**Issue by ndav1d** [hpjansson/chafa#69]
chafa is always outputting the image perfectly. probably because it's using another rendering method.. how can I force it to use chafa?
![image](https://user-images.githubusercontent.com/74260683/136008510-e74f8960-5a2a-4af7-99ae-684b7e5f9e72.png)

**Comment by ndav1d** [comment]
my bad, from the manpage
```man
       -f, --format format
           Set output format; one of [iterm, kitty, sixels, symbols]. The default is iterm, kitty
           or sixels if the connected terminal supports one of these, falling back to symbols
           ("ANSI art") otherwise.
```

**Comment by hpjansson** [comment]
Thanks for filing the issue anyway, it means there could be a documentation problem (maybe this option is too hard to find?).

There are probably places where the feature advertisements need to be updated too. Currently the README still describes Chafa as purely a character-art package, which is misleading. It can do a bit more now, and the default is to produce images that are as high-fidelity as possible, since I think that's what most users expect.

**Comment by ndav1d** [comment]
Well I think the users should always do something I didn't do this time... `read the manpages!`

The docs are well written and clear enough
```
       -f, --format format
           Set output format; one of [iterm, kitty, sixels, symbols]. The default is iterm, kitty
           or sixels if the connected terminal supports one of these, falling back to symbols
           ("ANSI art") otherwise.
```

But maybe mention it in the `README` as well :D
