### ISSUE TITLE
make freetype dependency internal

### ISSUE THREAD

**Issue by satmandu** [hpjansson/chafa#80]
Packages like harfbuzz are able to build freetype and link to it without having to have freetype installed first.

Any chance of doing that with chafa?

I'm a developer with Chromebrew, and I'm trying to reduce circular dependencies, and we're building harfbuzz against chafa... which depends upon freetype... and it would be nice not to have a special freetype install just to build chafa against.

**Comment by satmandu** [comment]
Actually, if we build w/o tools we don't need freetype, do I have that correct?

**Comment by satmandu** [comment]
Figured it out, thanks!

**Comment by hpjansson** [comment]
Hi, you're correct. I've thought about this, since the circular dependency came up in openSUSE, but couldn't think of a better solution than splitting up the lib and tools into separate packages.

I'm curious -- how are you solving the problem? Are you able to build it in two passes (lib before, then tools after Harfbuzz)?

**Comment by satmandu** [comment]
We are just using the library, so we disabled building the tools, which let us avoid the circular dependency. Previously we were using a two stage build.
